/******************************************************************************
* This file was generated by ZenStack CLI 2.9.4.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

export * from './test-item';
export { getQueryKey } from '@zenstackhq/tanstack-query/runtime-v5';
export { VueQueryContextKey, provideHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/vue';
export { default as metadata } from './__model_meta';
